options:
  apt-repository:
    type: string
    default: "deb http://packages.elasticsearch.org/logstash/1.4/debian stable main"
    description: A sources.list entry line.
  apt-key-url:
    type: string
    default: "http://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    description: The URL for the key for the APT repository.
  extra_config:
    type: string
    default: ""
    description: Extra configuration for logstash.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
         juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup.
