#!/usr/bin/python3

import amulet

d = amulet.Deployment(series='trusty')

d.add('logstash')

# Don't forget to expose using d.expose(service)

try:
    d.setup(timeout=900)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise

